### ISSUE TITLE
Tampilan Mobile

### ISSUE THREAD

**Issue by hawariMuflihMunte** [MuhammAdFariz02/Kostumku#1]
Kurang responsif, tampilan pada perangkat mobile berantakan, dan lain-lain

**Comment by MuhammAdFariz02** [comment]
aman aman :v

**Comment by MuhammAdFariz02** [comment]
pulang gasss... ngantuk boi udah jam 2

**Comment by hawariMuflihMunte** [comment]
Sebagai Developer (nya sendiri), saya sedikit kecewa :cry:

**Comment by MuhammAdFariz02** [comment]
ada pulakkkkk

**Comment by hawariMuflihMunte** [comment]
Lain kali kalau ada waktu, kita revisi besar-besaran :anger: :angry: :anger:

**Comment by hawariMuflihMunte** [comment]
Emg masih cupu kita boy :-1: :boy:

**Comment by MuhammAdFariz02** [comment]
astaghfirullah

**Comment by MuhammAdFariz02** [comment]
naishhh brader github #stayhalal

**Comment by hawariMuflihMunte** [comment]
Uhmmm, klo ada wqktu, gass desain + revisi woy :smile:

**Comment by hawariMuflihMunte** [comment]
#stayMotivated, #stayHalal, #stayConnected, #stayDeveloping, #stayWorking... 
Semangat Wibu

**Comment by MuhammAdFariz02** [comment]
hiyayayayaya

**Comment by hawariMuflihMunte** [comment]
Ternyata ko cek" juga ya komentar di sini

**Comment by hawariMuflihMunte** [comment]
Alhamdulillah project yang kemarin aku tangani dapat izin untuk up ke GitHub

**Comment by hawariMuflihMunte** [comment]
Kita cari developer lainnnya cok....
Kita perlu developer yang jago biar kita bisa ikut pande juga
